### ISSUE TITLE
Broken Linux and macOS Build

### ISSUE THREAD

**Issue by vojtamolda** [mwl4/ConverterPIX#1]
When trying to build the project on macOS (_10.12.4_, _clang 8.1.0_) or Linux (_Ubuntu 16.04_, _gcc 5.4.0_) the project fails to build with the following error message:

```
$ make
...
g++ -c -g -w -O2 -Wall -std=c++14 -msse -msse2 -fpermissive -I./ -I./libs/glm -I./libs/fmt file.cpp -o file.o
In file included from file.cpp:10:0:
file.h:85:17: error: conflicting declaration ‘typedef class FileStd File’
 typedef FileStd File;
                 ^
In file included from file.h:12:0,
                 from file.cpp:10:
./prerequisites.h:91:7: note: previous declaration as ‘class File’
 class File;
       ^
file.cpp: In member function ‘virtual bool FileStd::open(const string&, const char*)’:
file.cpp:36:43: error: ‘directoryExists’ was not declared in this scope
   if (!directoryExists(directory(filepath)) && strchr(attr, 'w') != nullptr)
                                           ^
file.cpp:38:43: error: ‘createDirectory’ was not declared in this scope
    if (createDirectory(directory(filepath)))
                                           ^
file.cpp: In function ‘bool createDirectory(const string&)’:
file.cpp:118:34: error: ‘directoryExists’ was not declared in this scope
  if (directoryExists(dirr.c_str())) {
                                  ^
file.cpp:124:51: error: ‘directoryExists’ was not declared in this scope
   if (!directoryExists(dirr.substr(0, pos).c_str()))
                                                   ^
file.cpp: In function ‘bool copyFile(const char*, const char*)’:
file.cpp:212:8: error: aggregate ‘File fw’ has incomplete type and cannot be defined
   File fw;
        ^
file.cpp: In function ‘std::vector<std::__cxx11::basic_string<char> > listFilesInDirectory(const string&, bool)’:
file.cpp:294:54: error: too few arguments to function ‘std::vector<std::__cxx11::basic_string<char> > listFilesInDirectory(const string&, bool)’
     auto subdir = listFilesInDirectory(full_file_name);
                                                      ^
file.cpp:244:26: note: declared here
 std::vector<std::string> listFilesInDirectory(const std::string &directory, boo
                          ^
makefile:28: recipe for target 'file.o' failed
...
```

I didn't check Windows, but I think it wouldn't build as well. These look like legitimate C++ errors. There's probably a few functions missing inside of the `src/file.h` that are needed in `src/file.c` or something like that.

**Comment by mwl4** [comment]
Looks like you are trying to compile some old version of the tool. Try to compile code from the last commit.

**Comment by mwl4** [comment]
More precisely it looks like you are compiling old file.cpp (including file.h). There is no longer class named FileStd. However, even older versions of code (if each part of code is taken from one date) should compile on different platforms.

**Comment by vojtamolda** [comment]
Hello @mwl4,

Thanks for your answers and time. I'm building the latest commit from here (`8456ce`). Is this the official repository of the project or is there some other location?

At the moment, I see these problems (all of them are easily fixable and I can submit a PR if you want):

1. It looks like `src/file.[c,h]` shouldn't exist. Part of the code in this file is placed in `src/fs/filesystem.[c,h]`. Probably some forgotten leftover pieces of code after refactoring. Maybe these files are not part of any MS VS projects so these build, but `make` uses `*.cpp` wildcards, picks them up, tries to build them and fails.

2. `FileStd` isn't really used anywhere except `copyFile(...)` which can be easily rewritten without it by using just `fwrite(...)` from the standard C library.

3. There are two duplicate and identical versions of `main(...)` one in `src/_main.c` and one in `src/cmd/_main.c`. I guess the version in `cmd/` is used by MS VS and the one in `src` by other platforms?

4. `strip` command has a slightly different syntax on _macOS_ and _Linux_. The `-s` option doesn't work. However, this should probably be solved in a different issue. Technically, _macOS_ isn't listed as an officially supported platform.

**Comment by mwl4** [comment]
Truth. I am going to remove unneccessary files in a while. Always I use internal repository, that is why files are not removed here.

**Comment by mwl4** [comment]
Fixed.
