### ISSUE TITLE
"Invalid parameters" when only -b specified on Linux

### ISSUE THREAD

**Issue by mik13ST** [mwl4/ConverterPIX#3]
Hello,
I have extracted the `base.scs` into my `base` directory inside ETS2 root directory. I placed the `converter_pix` linux executable into the ETS2 root folder to make it as simple as possible. Yet it still does not work. 

My ETS2 root dir looks like this:
`base/          base.scs*  controller.vdf*  core.scs*  def.scs*     licenses/    readme.rtf*
base_cfg.scs*  bin/       converter_pix*   def/       effect.scs*  locale.scs*  tools/`

When I run `.../Euro Truck Simulator 2$ ./converter_pix -b ./base` I get 

>  \******************************************
 **        Converter PMX to PIX          **
 **       Copyright (C) 2017 mwl4        **
 \******************************************
Invalid parameters

I was trying to convert just one model, but file not found error kept occurring, so I decided to try this first. Your tool should be able to do this like this (as of help and README.md).

What could be the problem? I am running Xubuntu 17.04. Should I try to compile it on my machine and see if it fixes it? Or are the any differences between using your tool on Windows and Linux?

Thanks.

**Comment by mwl4** [comment]
If you want to convert whole base, then you should not use -b parameter. 
Run: ./converter_pix ./base
-b parameter might be used to specify more base paths in the UFS.

**Comment by mik13ST** [comment]
Oh, ok ... didn't realize that, I must have overlooked that on the help page.
Sorry for creating issue that not really is an issue. It's my misunderstanding of the help page.
