### ISSUE TITLE
Skipping folders?

### ISSUE THREAD

**Issue by umustbeloggedintododat** [mwl4/ConverterPIX#39]
I'm trying to convert the Ai Traffic Pack by Jazzycat, but the exported version contains less folders than the original. What happened?

**Comment by umustbeloggedintododat** [comment]
It keeping on stopping at around 33% why is this happening >:(

**Comment by umustbeloggedintododat** [comment]
PLEASE HELP ME!!!13ERTERT

**Comment by umustbeloggedintododat** [comment]
I found out what is causing it to stop. It's the folders porsche_cayenne_09 and vw_beetle. Removing those folders caused it to complete.

**Comment by mwl4** [comment]
Is this still a problem?

**Comment by mwl4** [comment]
Closing as did not receive more information. Reopen if you need.
