### ISSUE TITLE
Need a update for 1.50 beta

### ISSUE THREAD

**Issue by felipedorea** [mwl4/ConverterPIX#50]
Hi. im using the 1.50 experimental beta and SCS launched the new extractor and blender files etc... But converterPIX isn`t working more, the browser keep empty when imports the scs models... I think needs a compatbility update. Do you have some intention to update before the official 1.50 version? For beta users like me? If not no problem... but would be nice hehe :) ...Thx.

**Comment by mwl4** [comment]
Hello,
update is almost done: https://github.com/mwl4/ConverterPIX/pull/49
I think it is matter of a day to get it fully working.

**Comment by felipedorea** [comment]
Woooow, nice!!

**Comment by mwl4** [comment]
Closing, as new version of ConverterPIX has been released.
