### ISSUE TITLE
Program finishing in the middle

### ISSUE THREAD

**Issue by celinha02** [mwl4/ConverterPIX#51]
So, I'm getting what I think is an error, where the program stop in some tobj and close, I think that is an error, but also not sure if I'm doing someting wrong.

![image](https://github.com/mwl4/ConverterPIX/assets/166999136/b26b0bfe-1279-4ed2-b80b-e0e5a5a3bc3a)

**Comment by mwl4** [comment]
Could you please provide more details? What command exactly are you trying to run? Do you try to convert original game files or some modification? Is it about 1.50 update?

**Comment by celinha02** [comment]
The command I used is .\converter_pix.exe .\vehicle
I was trying to convert the original game files ans yes it is 1.50 version, this error, if is an error, happened on the file /material/environment/brushed_reflection/brushed_reflection.tobj the scs file is base_share.scs

**Comment by mwl4** [comment]
It should be fixed now. Update converter_pix binary.
