### ISSUE TITLE
The converter does not work correctly if metadata table not compressed

### ISSUE THREAD

**Issue by SerzhSmith** [mwl4/ConverterPIX#56]
If metadata table not compressed, the code below does not work properly.
/src/fs/hashfs_v2.cpp:376 
`if( !m_root->blockRead( m_metadataTable.data(), m_header.m_metadata_table_offset, m_metadataTable.size() ) )`
maybe you meant
`if( !m_root->blockRead( m_metadataTable.data(), m_header.m_metadata_table_offset, metadataTableSize) )`  ?

**Comment by mwl4** [comment]
Hello,

you are right. I am applying fix and releasing new binary.
