### ISSUE TITLE
Error when trying to extract/convert DDS "format R16G16_UNORM(35) is not supported"

### ISSUE THREAD

**Issue by dariowouters** [mwl4/ConverterPIX#57]
Hi,

Program seems to be unable to convert DAF XF euro6 interior model with the `/vehicle/truck/daf_xf_euro6/carpaint_n.dds` file being the issue due to the dds file being in an unsupported format.

```
> ./converter_pix.exe -b ./base_vehicle.scs -e ./out -t /vehicle/truck/daf_xf_euro6/carpaint_n.tobj

 ******************************************
 **        Converter PMX to PIX          **
 **       Copyright (C) 2024 mwl4        **
 ******************************************

<error> [dds] /vehicle/truck/daf_xf_euro6/carpaint_n.dds: File cannot be converted, as format R16G16_UNORM(35) is not supported!
<error> [tobj] /vehicle/truck/daf_xf_euro6/carpaint_n.tobj: Unable to convert DDS '/vehicle/truck/daf_xf_euro6/carpaint_n.dds' to non-DXT10 format.
Unable to convert tobj to old formats: /vehicle/truck/daf_xf_euro6/carpaint_n.tobj
```

Would it be possible to add support for the `R16G16_UNORM` format?
Thanks.

**Comment by mwl4** [comment]
Hello, your issue has been addressed in https://github.com/mwl4/ConverterPIX/commit/258b2e06d028640dea971b38503334fe1db338ac commit. Update ConverterPIX executable please.
Reopen issue if it is still the issue.
