### ISSUE TITLE
Error when opening prefab v24 files

### ISSUE THREAD

**Issue by OnYx9** [mwl4/ConverterPIX#58]
Hello,

When trying to convert new prefabs added with v1.50 (ATS) the converter crashes with the following error:
![image](https://github.com/mwl4/ConverterPIX/assets/32908087/bdedbc76-a822-451f-a047-3f501eda8b7a)

Is it possible to add support for the new prefab files?
Thanks.

**Comment by nexus9192** [comment]
Any update to this? Having the same issue here

**Comment by mwl4** [comment]
It should be fixed now. Update ConverterPIX executable.
Reopen the issue if there is some problem with importing new prefabs.
